repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        name: Ensure correct trailing whitespace
    -   id: end-of-file-fixer
        name: Fix EOF
    -   id: check-yaml
        name: Check YAML formatting

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
    -   id: ruff
        name: Enforce Ruff rules
    -   id: ruff-format
        name: Auto-formatting Python code

-   repo: local
    hooks:
      - id: check-django-debug
        name: Ensure Django DEBUG setting is False
        entry: bash -c 'if grep -q "DEBUG = True" sysmonify/settings.py; then echo "DEBUG is True — fix before commit."; exit 1; fi'
        language: system
        pass_filenames: false
