name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run pytest
        run: pytest

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5.1.2

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage
          path: coverage.xml
        if: ${{ always() }}

      - name: Ruff check
        run: ruff check
